baseURL: 'https://ubuntu-uk.org'
languageCode: en-gb
title: 'Ubuntu UK Community'
theme: "ubuntukr"
buildFuture: true
#googleAnalytics: ""
params:
  contact: contact@ubuntu-kr.org
  #facebook: ubuntukorea
  #twitter: UbuntuKrOrg
  github: ubuntu-uk
  launchpad: ubuntu-uk
  mastodon: https://floss.social/@ubuntu_UK
  #youtube: https://www.youtube.com/user/UbuntuKorea
  #linkedin: https://www.linkedin.com/company/ubuntu-kr/
  source_repo: https://github.com/ubuntu-uk/ubuntu-uk.github.io
  #privacyPolicy: https://disclosures.ubuntu-kr.org/privacy-policy/
defaultContentLanguage: en
languages:
  en:
    languageName: English
    title: Ubuntu UK Community
    weight: 2
    params:
      description: >-
        Ubuntu UK Community is a Ubuntu LoCo (Local Community) in the UK. 
        It is a place for everyone who intrested in using, developing with Ubuntu, or contributing to Ubuntu projects.
      copyright: >-
        © 2021 Ubuntu Korea Community (Ubuntu Korean LoCo Team).
        © 2021 Ubuntu UK Community (Ubuntu UK LoCo Team)
        Except where otherwise noted, Website source code licensed under MIT, Contents licensed under CC BY-SA 4.0. 
        Ubuntu and Canonical are registered trademarks of Canonical Ltd.
      main_slide:
        label: About the community
        link: about
    menu:
      main:
      - identifier: try
        name: Try Ubuntu
        weight: 1
      - identifier: download
        parent: try
        name: Download
        url: download
        weight: 20
      - identifier: hardware
        name: Ubuntu Certified Hardware
        parent: try
        url: https://ubuntu.com/certified
        weight: 20
      # - identifier: wiki-ko
      #   parent: try
      #   name: Wiki (Korean)
      #   url: https://wiki.ubuntu-kr.org
      #   weight: 20
      # - identifier: tutorials-ko
      #   parent: try
      #   name: Tutorials (Korean)
      #   url: https://ubuntu-kr.github.io/workshops/
      #   weight: 21
      - identifier: docs-en
        parent: try
        name: Docs
        url: https://docs.ubuntu.com
        weight: 22
      - identifier: tutorials-en
        parent: try
        name: Tutorials
        url: https://ubuntu.com/tutorials
        weight: 23
      - identifier: wiki-en
        parent: try
        name: Wiki
        url: https://wiki.ubuntu.com
        weight: 24
      - identifier: about-group
        name: About
        weight: 2
      # - identifier: about
      #   parent: about-group
      #   name: About our community
      #   url: about
      #   weight: 24
      # - identifier: bylaws
      #   parent: about-group
      #   name: Bylaws
      #   url: bylaws
      #   weight: 25
      # - identifier: sponsors
      #   parent: about-group
      #   name: Sponsors
      #   url: sponsors
      #   weight: 26
      - identifier: community
        name: Community
        url: community
        weight: 3
      - identifier: forum
        parent: community
        name: Forum (Discourse)
        url: https://discourse.ubuntu.com/c/locos/ubuntu-uk
        weight: 32
      # - identifier: fb-group
      #   parent: community
      #   name: Facebook Group
      #   url: https://www.facebook.com/groups/ubuntu.ko
      #   weight: 34
      - identifier: lists
        parent: community
        name: Mailing list
        url: https://lists.ubuntu.com/archives/ubuntu-uk/
        weight: 35
      - identifier: chat
        parent: community
        name: Chat 
        url: chat
        weight: 36
      # - identifier: partandcontrib
      #   name: Participate & Contribute
      #   url: partandcontrib
      #   weight: 4
      # - identifier: events
      #   parent: partandcontrib
      #   name: Join events
      #   url: https://event.ubuntu-kr.org
      #   weight: 4
      # - identifier: study_projects
      #   parent: partandcontrib
      #   name: Group Studies/Projects
      #   url: projects
      #   weight: 4
      # - identifier: translate
      #   parent: partandcontrib
      #   name: Translate Ubuntu
      #   url: translate
      #   weight: 4
      # - identifier: paid-membership
      #   parent: partandcontrib
      #   name: Contribute Membership fee
      #   url: https://github.com/sponsors/ubuntu-kr
      #   weight: 4
      - identifier: follow
        name: Follow us
        weight: 5
      # - identifier: blog
      #   parent: follow
      #   name: Blog
      #   url: https://blog.ubuntu-kr.org
      #   weight: 4
      # - identifier: facebook
      #   parent: follow
      #   name: Facebook
      #   url: https://fb.com/ubuntukorea
      #   weight: 4
      # - identifier: twitter
      #   parent: follow
      #   name: Twitter
      #   url: https://twitter.com/UbuntuKrOrg
        weight: 4
      # - identifier: youtube
      #   parent: follow
      #   name: YouTube
      #   url: https://www.youtube.com/user/UbuntuKorea
      #   weight: 4
      - identifier: mastodon
        parent: follow
        name: Mastodon
        url: https://floss.social/@ubuntu_UK
        weight: 4
      # - identifier: linkedin
      #   parent: follow
      #   name: LinkedIn
      #   url: https://www.linkedin.com/company/ubuntu-kr/
      #   weight: 4
